server:
  port: 8201
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=CSTimoocdemo?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=CST
    username: root   # 可能需要改
    password: 123456