server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=CSTimoocdemo?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=CST
    username: root
    password: 123456